### ISSUE TITLE
DietPi-Software | PiJuice

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1488]
> https://github.com/PiSupply/PiJuice/tree/master/Software

**Comment by Fourdee** [comment]
G_AGI pijuice-base python-smbus i2c-tools
```
G_AGI pijuice-base
root@DietPi:~# /usr/bin/pijuice_sys.py
Traceback (most recent call last):
  File "/usr/bin/pijuice_sys.py", line 10, in <module>
    from pijuice import *
  File "/usr/lib/python2.7/dist-packages/pijuice.py", line 3, in <module>
    from smbus import SMBus
ImportError: No module named smbus

G_AGI python-smbus i2c-tools
root@DietPi:~# /usr/bin/pijuice_sys.py
Traceback (most recent call last):
  File "/usr/bin/pijuice_sys.py", line 259, in <module>
    main()
  File "/usr/bin/pijuice_sys.py", line 173, in main
    open(configPath, 'w+').write(json.dumps(configData)).close()
AttributeError: 'NoneType' object has no attribute 'close'
```

🈯️ Overwrite config with default https://github.com/PiSupply/PiJuice/blob/master/Software/README.md#json-configuration-file

---

Firmware update
```
wget https://github.com/PiSupply/PiJuice/raw/master/Firmware/PiJuice-V1.1_2018_01_15.elf.binary -O package.binary
chmod +x package.binary
pijuiceboot 14 package.binary
```
---

🈯️ Simple poweroff test:
```
cat << _EOF_ > /root/pijuice_func1.sh
#!/bin/bash
poweroff
_EOF_
chmod +x /root/pijuice_func1.sh
```

Appears SW2 (```button_power_off```) is the only programmable button?
```
cat << _EOF_ > /var/lib/pijuice/pijuice_config.JSON
{
  "system_events": {
    "low_battery_voltage": {
      "function": "SYS_FUNC_HALT", 
      "enabled": true
    }, 
    "low_charge": {
      "function": "NO_FUNC", 
      "enabled": true
    }, 
    "button_power_off": {
      "function": "USER_FUNC1", 
      "enabled": true
    }, 
    "forced_power_off": {
      "function": "USER_FUNC2", 
      "enabled": true
    }, 
    "no_power": {
      "function": "SYS_FUNC_HALT_POW_OFF", 
      "enabled": true
    }, 
    "forced_sys_power_off": {
      "function": "USER_FUNC3", 
      "enabled": true
    }, 
    "watchdog_reset": {
      "function": "USER_EVENT", 
      "enabled": true
    }
  }, 
  "user_functions": {
    "USER_FUNC1": "$HOME/pijuice_func1.sh", 
    "USER_FUNC2": "$HOME/pijuice_func2.sh", 
    "USER_FUNC3": "$HOME/pijuice_func3.sh", 
    "USER_FUNC4": "", 
    "USER_FUNC5": "", 
    "USER_FUNC6": "", 
    "USER_FUNC7": "",
    "USER_FUNC8": ""
  }, 
  "system_task": {
    "watchdog": {
      "enabled": true, 
      "period": "60"
    }, 
    "min_bat_voltage": {
      "threshold": "1", 
      "enabled": true
    }, 
    "min_charge": {
      "threshold": "1", 
      "enabled": true
    }, 
    "enabled": true, 
    "wakeup_on_charge": {
      "enabled": true, 
      "trigger_level": "1"
    }
  }
}
_EOF_

**Comment by Fourdee** [comment]
Online doc: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=10740#p10740

**Comment by MichaIng** [comment]
Nice one 👍, I am just thinking to take one as power loss protection. On the other hand, my external powered HDD docking station would be not included anyway, holding data, database and swapfile 🤔.

**Comment by Fourdee** [comment]
Completed.
