### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by cosmicstorm27** [MichaIng/DietPi#2018]
--------------------------------------------------------------------
- DietPi has encounted an error, and, is unable to continue        -
- Please create a ticket: https://github.com/Fourdee/DietPi/issues -
- Copy and paste the BLUE lines below, into the ticket             -
--------------------------------------------------------------------

#### Details:
- Date           | Fri 17 Aug 23:38:27 AEST 2018
- BR sent?       | 1 : 6e852772-126c-431d-97e5-5de939cd64da
- DietPi version | v6.9
- Img creator    | 0
- Pre-image      | Raspbian Lite
- SBC device     | RPi 3 Model B (armv7l) (index=3)
- Distro         | stretch (index=4)
- Command        | occ maintenance:mode --on
- Exit code      | 1
- Software title | DietPi-Services

#### Additional logs:
```
Log file contents:
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/owncloud/lib/private/DB/Connection.php:62
Stack trace:
#0 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/owncloud/lib/private/DB/Connection.php(145): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\CommonentManager))
#6 /var/www/owncloud/lib/private/DB/ConnectionFactory.php(145): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\CommonentManager))
#7 /var/www/owncloud/lib/private/Server.php(526): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /var/www/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /var/www/owncloud/lib/private/Server.php(1211): OC\ServerContainer->query('DatabaseConnect...')
#12 /var/www/owncloud/lib/private/Server.php(402): OC\Server->getDatabaseConnection()
#13 /var/www/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#14 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('AppConfig')
#15 /var/www/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AppConfig')
#16 /var/www/owncloud/lib/private/Server.php(1140): OC\ServerContainer->query('AppConfig')
#17 /var/www/owncloud/lib/private/Server.php(580): OC\Server->getAppConfig()
#18 /var/www/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#19 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('AppManager')
#20 /var/www/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#21 /var/www/owncloud/lib/private/Server.php(1410): OC\ServerContainer->query('AppManager')
#22 /var/www/owncloud/lib/private/legacy/app.php(346): OC\Server->getAppManager()
#23 /var/www/owncloud/lib/private/legacy/app.php(110): OC_App::getEnabledApps()
#24 /var/www/owncloud/lib/base.php(586): OC_App::loadApps(Array)
#25 /var/www/owncloud/lib/base.php(1004): OC::init()
#26 /var/www/owncloud/console.php(64): require_once('/var/www/ownclo...')
#27 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#28 {main}

**Comment by Fourdee** [comment]
@akidiep 

Hi,

Thanks for the report 👍 

@MichaIng 
Any chance you could take a look at this one please?

**Comment by Fourdee** [comment]
Confirmed error on testing branch:
- 0 byte file
```
root@DietPi:~# ls -lha /var/www/nextcloud/config/config.php
-rw-r--r-- 1 www-data www-data 0 Aug 19 00:46 /var/www/nextcloud/config/config.php
```

![image](https://user-images.githubusercontent.com/7077026/44304060-475cbc00-a349-11e8-9272-623c0262b1ea.png)

Due to?
```
[ INFO ] DietPi-Software | Enable 4-byte support for MariaDB
[  OK  ] DietPi-Software | systemctl restart mysql
Failed loading /usr/lib/php/20151012/opcache.so:  /usr/lib/php/20151012/opcache.so: cannot open shared object file: Permission denied
```

**Comment by cosmicstorm27** [comment]
Hi there, already sorted. Thanks for looking at this issue.

**Comment by MichaIng** [comment]
@akidiep 
Great to here. I guess MariaDB was down, or pdo_mysql PHP module?

@Fourdee 
The Nextcloud occ installation must have been failed and thrown an error message.
`Failed loading /usr/lib/php/20151012/opcache.so:  /usr/lib/php/20151012/opcache.so: cannot open shared object file: Permission denied`
- Was this the only error message of that kind? If PHP failed, then the command line install failed. I will also try on VM.
**€: Could not replicate. Found and fixed minor issue on Jessie, but that did not break the install: https://github.com/Fourdee/DietPi/commit/9f826efee9523fb9e8a12a9a96668b0799752280**

**Comment by Fourdee** [comment]
@MichaIng 

> €: Could not replicate. Found and fixed minor issue on Jessie, but that did not break the install: 

Strange, issue occurred on my C2, fine on NanoPC-T4, trying reinstall + test again.

Full log:
```
[  OK  ] DietPi-Software | Setting in /etc/php/7.0/mods-available/opcache.ini adjusted: opcache.revalidate_freq=1
[ INFO ] DietPi-Software | Lighttpd webserver found, enable Nextcloud specific configuration.
[  OK  ] DietPi-Software | Added setting        "mod_setenv", to /etc/lighttpd/lighttpd.conf after line         "mod_access",
[  OK  ] DietPi-Software | cp -f /DietPi/dietpi/conf/lighttpd.nextcloud.conf /etc/lighttpd/conf-available/99-dietpi-nextcloud.conf
Enabling dietpi-nextcloud: ok
Run "service lighttpd force-reload" to enable changes
[ INFO ] DietPi-Software | Enable 4-byte support for MariaDB
[  OK  ] DietPi-Software | systemctl restart mysql
Failed loading /usr/lib/php/20151012/opcache.so:  /usr/lib/php/20151012/opcache.so: cannot open shared object file: Permission denied
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mysqlnd.so' - /usr/lib/php/20151012/mysqlnd.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo.so' - /usr/lib/php/20151012/pdo.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/xml.so' - /usr/lib/php/20151012/xml.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/apcu.so' - /usr/lib/php/20151012/apcu.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/calendar.so' - /usr/lib/php/20151012/calendar.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/ctype.so' - /usr/lib/php/20151012/ctype.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/curl.so' - /usr/lib/php/20151012/curl.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/dom.so' - /usr/lib/php/20151012/dom.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/exif.so' - /usr/lib/php/20151012/exif.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/fileinfo.so' - /usr/lib/php/20151012/fileinfo.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/ftp.so' - /usr/lib/php/20151012/ftp.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/gd.so' - /usr/lib/php/20151012/gd.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/gettext.so' - /usr/lib/php/20151012/gettext.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/iconv.so' - /usr/lib/php/20151012/iconv.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/igbinary.so' - /usr/lib/php/20151012/igbinary.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/intl.so' - /usr/lib/php/20151012/intl.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/json.so' - /usr/lib/php/20151012/json.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mbstring.so' - /usr/lib/php/20151012/mbstring.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mcrypt.so' - /usr/lib/php/20151012/mcrypt.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mysqli.so' - /usr/lib/php/20151012/mysqli.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_mysql.so' - /usr/lib/php/20151012/pdo_mysql.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_sqlite.so' - /usr/lib/php/20151012/pdo_sqlite.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/phar.so' - /usr/lib/php/20151012/phar.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/posix.so' - /usr/lib/php/20151012/posix.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/readline.so' - /usr/lib/php/20151012/readline.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/redis.so' - /usr/lib/php/20151012/redis.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/shmop.so' - /usr/lib/php/20151012/shmop.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/simplexml.so' - /usr/lib/php/20151012/simplexml.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/sockets.so' - /usr/lib/php/20151012/sockets.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/sqlite3.so' - /usr/lib/php/20151012/sqlite3.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/sysvmsg.so' - /usr/lib/php/20151012/sysvmsg.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/sysvsem.so' - /usr/lib/php/20151012/sysvsem.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/sysvshm.so' - /usr/lib/php/20151012/sysvshm.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/tokenizer.so' - /usr/lib/php/20151012/tokenizer.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/wddx.so' - /usr/lib/php/20151012/wddx.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/xmlreader.so' - /usr/lib/php/20151012/xmlreader.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/xmlwriter.so' - /usr/lib/php/20151012/xmlwriter.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/xsl.so' - /usr/lib/php/20151012/xsl.so: cannot open shared object file: Permission denied in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/zip.so' - /usr/lib/php/20151012/zip.so: cannot open shared object file: Permission denied in Unknown on line 0
An unhandled exception has been thrown:
Error: Call to undefined function OC\Files\json_encode() in /var/www/nextcloud/lib/private/Files/Filesystem.php:808
Stack trace:
#0 /var/www/nextcloud/lib/private/Files/Filesystem.php(583): OC\Files\Filesystem::normalizePath('')
#1 /var/www/nextcloud/lib/private/Files/View.php(109): OC\Files\Filesystem::isValidPath('')
#2 /var/www/nextcloud/lib/private/Server.php(193): OC\Files\View->__construct()
#3 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#4 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('EncryptionManag...')
#5 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('EncryptionManag...')
#6 /var/www/nextcloud/lib/private/Server.php(1229): OC\ServerContainer->query('EncryptionManag...')
#7 /var/www/nextcloud/lib/base.php(866): OC\Server->getEncryptionManager()
#8 /var/www/nextcloud/lib/base.php(738): OC::registerEncryptionWrapper()
#9 /var/www/nextcloud/lib/base.php(1081): OC::init()
#10 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#11 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#12 {main}PHP Fatal error:  Uncaught Error: Call to undefined function OC\Log\json_encode() in /var/www/nextcloud/lib/private/Log/File.php:128
Stack trace:
#0 [internal function]: OC\Log\File::write('PHP', 'PHP Startup: Un...', 3)
#1 /var/www/nextcloud/lib/private/Log.php(330): call_user_func(Array, 'PHP', 'PHP Startup: Un...', 3)
#2 /var/www/nextcloud/lib/private/Log.php(180): OC\Log->log(3, 'PHP Startup: Un...', Array)
#3 /var/www/nextcloud/lib/private/Log/ErrorHandler.php(68): OC\Log->critical('PHP Startup: Un...', Array)
#4 [internal function]: OC\Log\ErrorHandler::onShutdown()
#5 {main}
  thrown in /var/www/nextcloud/lib/private/Log/File.php on line 128
```

**Comment by Fourdee** [comment]
@MichaIng 

🈯️ Fresh image install + update to testing is fine

Device hasn't been re-flashed for over 2 months, been using it as a testing system, so non-issue.

Marking as closed, please reopen if required.
