### ISSUE TITLE
DietPi-Software | Airsonic: Bullseye/Java 17 support and active fork

### ISSUE THREAD

**Issue by Andaloup** [MichaIng/DietPi#4847]
#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
```
_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=6
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='not applicable'
G_LIVE_PATCH_STATUS[1]='applied'
G_LIVE_PATCH_STATUS[2]='applied'
G_LIVE_PATCH_STATUS[3]='applied'
G_LIVE_PATCH_STATUS[4]='applied'
```
- Distro version | `echo $G_DISTRO_NAME $G_RASPBIAN`
`bullseye 0`

- Kernel version | `uname -a`
`Linux DietPi 5.10.63-v8+ #1459 SMP PREEMPT Wed Oct 6 16:42:49 BST 2021 aarch64 GNU/Linux`

- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
`RPi 4 Model B (aarch64)`

- Power supply used
`5V 3A`

- SDcard used 
`SanDisk ultra 32GB`

#### Additional Information 
- Software title
`Airsonic`

- Was the software title installed freshly or updated/migrated?
`installed freshly`

- Can this issue be replicated on a fresh installation of DietPi?
`Yes`

#### Steps to reproduce
1. Install Airsonic with `dietpi-software`
2. after install no conection to `http://<my.ip>:8080/airsonic`

#### Expected behaviour
Connection to airsonic-server

#### Actual behaviour
no connection, similar issue #3318

#### Extra details

My running services
- lighttpd
- openssh
- php7.4
- pi-hole-ftl

`java -version`
```
openjdk version "17-ea" 2021-09-14
OpenJDK Runtime Environment (build 17-ea+19-Debian-1)
OpenJDK 64-Bit Server VM (build 17-ea+19-Debian-1, mixed mode, sharing)
```

`journalctl -u airsonic`
```
Oct 16 13:51:06 DietPi systemd[1]: Started Airsonic Media Server (DietPi).
Oct 16 13:51:14 DietPi Airsonic[89762]:            _                       _
Oct 16 13:51:14 DietPi Airsonic[89762]:      /\   (_)                     (_)
Oct 16 13:51:14 DietPi Airsonic[89762]:     /  \   _ _ __  ___  ___  _ __  _  ___
Oct 16 13:51:14 DietPi Airsonic[89762]:    / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|
Oct 16 13:51:14 DietPi Airsonic[89762]:   / ____ \| | |   \__ \ (_) | | | | | (__
Oct 16 13:51:14 DietPi Airsonic[89762]:  /_/    \_\_|_|   |___/\___/|_| |_|_|\___|
Oct 16 13:51:14 DietPi Airsonic[89762]:                                                
Oct 16 13:51:14 DietPi Airsonic[89762]:                         10.6.2-RELEASE
Oct 16 13:51:15 DietPi Airsonic[89762]: 2021-10-16 13:51:15.950  INFO --- org.airsonic.player.Application          : Starting Application v10.6.2-RELEASE on DietPi with PID 89762 (/mnt/76804894-e391-4dc1-9af8-07aaf6ef0c00/dietpi_userdata/airsonic/airsonic.war started by airsonic in /mnt/76804894-e391-4dc1-9af8-07aaf6ef0c00/dietpi_userdata/airsonic)
Oct 16 13:51:15 DietPi Airsonic[89762]: 2021-10-16 13:51:15.970  INFO --- org.airsonic.player.Application          : The following profiles are active: legacy
Oct 16 13:51:23 DietPi Airsonic[89762]: 2021-10-16 13:51:23.469 ERROR --- o.s.boot.SpringApplication               : Application startup failed
Oct 16 13:51:23 DietPi Airsonic[89762]: java.lang.IllegalStateException: Cannot load configuration class: org.airsonic.player.Application
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:404) ~[spring-context-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:249) ~[spring-context-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:283) ~[spring-context-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:127) ~[spring-context-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687) ~[spring-context-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524) ~[spring-context-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:123) ~[spring-boot-1.5.22.RELEASE.jar!/:1.5.22.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:666) ~[spring-boot-1.5.22.RELEASE.jar!/:1.5.22.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:353) ~[spring-boot-1.5.22.RELEASE.jar!/:1.5.22.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.boot.SpringApplication.run(SpringApplication.java:300) ~[spring-boot-1.5.22.RELEASE.jar!/:1.5.22.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:135) ~[spring-boot-1.5.22.RELEASE.jar!/:1.5.22.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.airsonic.player.Application.main(Application.java:207) ~[classes!/:10.6.2-RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[airsonic.war:10.6.2-RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[airsonic.war:10.6.2-RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[airsonic.war:10.6.2-RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) ~[airsonic.war:10.6.2-RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]: Caused by: java.lang.ExceptionInInitializerError: null
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.context.annotation.ConfigurationClassEnhancer.newEnhancer(ConfigurationClassEnhancer.java:122) ~[spring-context-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:110) ~[spring-context-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:394) ~[spring-context-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         ... 19 common frames omitted
Oct 16 13:51:23 DietPi Airsonic[89762]: Caused by: org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @449b2d27
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:464) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:174) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:153) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         ... 22 common frames omitted
Oct 16 13:51:23 DietPi Airsonic[89762]: Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @449b2d27
Oct 16 13:51:23 DietPi Airsonic[89762]:         at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[na:na]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[na:na]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[na:na]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at java.base/java.lang.reflect.Method.setAccessible(Method.java:193) ~[na:na]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.ReflectUtils$1.run(ReflectUtils.java:61) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at java.base/java.security.AccessController.doPrivileged(AccessController.java:554) ~[na:na]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:52) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:243) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 16 13:51:23 DietPi Airsonic[89762]:         ... 34 common frames omitted
Oct 16 13:51:23 DietPi systemd[1]: airsonic.service: Main process exited, code=exited, status=1/FAILURE
Oct 16 13:51:23 DietPi systemd[1]: airsonic.service: Failed with result 'exit-code'.
Oct 16 13:51:23 DietPi systemd[1]: airsonic.service: Consumed 52.311s CPU time.

```

**Comment by MichaIng** [comment]
Many thanks for your report.

Airsonic has been achieved: https://github.com/airsonic/airsonic
It doesn't seem to support Java 17.

But there is a fork: https://github.com/airsonic-advanced/airsonic-advanced
I just wanted to test it and implement it as drop-in replacement. You can try it easily:
```sh
curl -sSfL 'https://github.com/airsonic-advanced/airsonic-advanced/releases/download/v10.6.0/airsonic.war' -o /mnt/dietpi_userdata/airsonic/airsonic.war
systemctl restart airsonic
```
That one is moreless of the same age as the latest original Airsonic, but it is worked on a new v11 version as well. To test that one:
```sh
curl -sSfL 'https://github.com/airsonic-advanced/airsonic-advanced/releases/download/11.0.0-SNAPSHOT.20211014191809/airsonic.war' -o /mnt/dietpi_userdata/airsonic/airsonic.war
systemctl restart airsonic
```

**Comment by MichaIng** [comment]
PR is open to migrate to Airsonic-Advanced: #4948
I just face two issues:
1. On a fresh install on Bullseye with Java 17, playback and query handling does not work without first manually removing and re-adding the player: https://github.com/airsonic-advanced/airsonic-advanced/issues/646
2. Initial access to the web interface is extremely slow. When a page or button/action was used the first time, which has a several seconds delay, then it reacts faster, but on a fresh installation where you naturally navigate though several pages, the first impression is extremely bad, so I guess many users remove it directly and use another media streamer: https://github.com/airsonic-advanced/airsonic-advanced/issues/602
    But this is the same with the current/original Airsonic, and with all OpenJDK versions, it seems to be a bug in the Java internal Tomcat for WAR handling.

**Comment by MichaIng** [comment]
Migration merged.
