### ISSUE TITLE
DietPi-Software | Node-Red and MQTT/Mosquitto

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#614]

**Comment by Fourdee** [comment]
MQTT: https://mosquitto.org/2013/01/mosquitto-debian-repository/

🈯️ Done. Not available for ARM64.

**Comment by Fourdee** [comment]
Node red:
Fails to install due to serialport GitHub download lacking ARM binary:
```
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.6/serialport-v4.0.6-node-v51-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.6 and node@7.2.1 (node-v51 ABI) (falling back to source compile with node-gyp)
```

Fails to compile:
```
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.6/serialport-v4.0.6-node-v51-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.6 and node@7.2.1 (node-v51 ABI) (falling back to source compile with node-gyp)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.2.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-red/node_modules/serialport/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/node-red/node_modules/serialport/build'
make: *** No rule to make target '../.node-gyp/7.2.1/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/local/lib/node_modules/node-red/node_modules/serialport/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.4.39-s5p6818
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/node-red/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/usr/local/lib/node_modules/node-red/node_modules/serialport/build/Release"
gyp ERR! cwd /usr/local/lib/node_modules/node-red/node_modules/serialport
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/node-red/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/usr/local/lib/node_modules/node-red/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-red/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 3.4.39-s5p6818
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-red/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/node-red/node_modules/serialport
node-pre-gyp ERR! node -v v7.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/node-red/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/usr/local/lib/node_modules/node-red/node_modules/serialport/build/Release' (1)
/usr/local/lib
└── node-red@0.15.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@4.0.6 (node_modules/node-red/node_modules/serialport):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@4.0.6 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

```

**Comment by Fourdee** [comment]
Data dir for Node-Red:
```
"$FP_DIETPI_USERDATA_DIRECTORY"/node-red
```

**Comment by Fourdee** [comment]
Port for node-red:
http://ip:1880

**Comment by Fourdee** [comment]
Done

**Comment by Fourdee** [comment]
Add Mosquito support for ARM64, using 32bit binaries. Tested fine on C2:
https://github.com/Fourdee/DietPi/issues/653#issuecomment-267817196

**Comment by Fourdee** [comment]
Done
