### ISSUE TITLE
Spotify user needed: Please help me test Spotify Connect Web!

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#6418]
Hey guys, someone out there with a Spotify account and an ARMv7 SBC to test whether Spotify Connect Web is actually still working?
```sh
dietpi-software install 141
journalctl -u spotify-connect-web
```
There was no GitHub + Spotify user involved when this software title was added, so I have nobody to ping: https://github.com/MichaIng/DietPi/issues/863

Its development stalled in 2018, the latest "release" has "alpha" in its name and the Spotify Connect library used is deprecated since at least 2018 as well and seems to not work anymore: https://github.com/Fornoth/spotify-connect-web/issues/146#issuecomment-422124995

It has basically decided that it will be removed, but as there are still some hundred reported installs, if it does still work, we may wait for the removal until about end of the year when Debian Buster support is dropped in DietPi.

There are alternatives, Raspotify and Spotifyd, depending on architecture, but both do not have a handy web interface, but do work with Spotify Connect apps.
__________
I was trying to test it on Debian Bookworm, but at least on NanoPi M1 it get different error messages depending on how I invoke it:
```console
root@NanoPiM1:/mnt/dietpi_userdata/spotify-connect-web# ./spotify-connect-web
Loading Spotify library...
Last.fm: incomplete credentials, not launched
Segmentation fault
root@NanoPiM1:/mnt/dietpi_userdata/spotify-connect-web# sudo -u dietpi ./spotify-connect-web
Loading Spotify library...
Last.fm: incomplete credentials, not launched
free(): double free detected in tcache 2
Aborted
root@NanoPiM1:/mnt/dietpi_userdata/spotify-connect-web# journalctl -u spotify-connect-web.service
-- Journal begins at Tue 2023-06-06 19:59:17 CEST, ends at Tue 2023-06-06 20:48:18 CEST. --
Jun 06 19:59:22 NanoPiM1 systemd[1]: Started Spotify Connect Web (DietPi).
Jun 06 19:59:24 NanoPiM1 spotify-connect-web[435]: Loading Spotify library...
Jun 06 19:59:24 NanoPiM1 spotify-connect-web[435]: Last.fm: incomplete credentials, not launched
Jun 06 19:59:24 NanoPiM1 spotify-connect-web[435]: Traceback (most recent call last):
Jun 06 19:59:24 NanoPiM1 spotify-connect-web[435]:   File "loader.py", line 3, in <module>
Jun 06 19:59:24 NanoPiM1 spotify-connect-web[435]:   File "runpy.py", line 180, in run_module
Jun 06 19:59:24 NanoPiM1 spotify-connect-web[435]:   File "runpy.py", line 72, in _run_code
Jun 06 19:59:24 NanoPiM1 spotify-connect-web[435]:   File "/mnt/dietpi_userdata/spotify-connect-web/main.py", line 15, in <module>
Jun 06 19:59:24 NanoPiM1 spotify-connect-web[435]:     from connect import Connect
Jun 06 19:59:24 NanoPiM1 spotify-connect-web[435]:   File "/mnt/dietpi_userdata/spotify-connect-web/connect.py", line 9, in <module>
Jun 06 19:59:24 NanoPiM1 spotify-connect-web[435]:     from console_callbacks import audio_arg_parser, mixer, error_callback, connection_callbacks, debug_callbacks, playback_callbacks, playback_setup
Jun 06 19:59:24 NanoPiM1 spotify-connect-web[435]:   File "/mnt/dietpi_userdata/spotify-connect-web/console_callbacks.py", line 25, in <module>
Jun 06 19:59:24 NanoPiM1 spotify-connect-web[435]:     audio_arg_parser.add_argument('--mixer', '-m', help='alsa mixer name for volume control', default=alsa.mixers()[0])
Jun 06 19:59:24 NanoPiM1 spotify-connect-web[435]: alsaaudio.ALSAAudioError: Invalid argument [default]
Jun 06 19:59:24 NanoPiM1 spotify-connect-web[435]: Failed to execute script loader
Jun 06 19:59:24 NanoPiM1 systemd[1]: spotify-connect-web.service: Main process exited, code=exited, status=255/EXCEPTION
Jun 06 19:59:24 NanoPiM1 systemd[1]: spotify-connect-web.service: Failed with result 'exit-code'.
Jun 06 19:59:24 NanoPiM1 systemd[1]: spotify-connect-web.service: Consumed 1.912s CPU time.
root@NanoPiM1:/mnt/dietpi_userdata/spotify-connect-web# python3 main.py
Traceback (most recent call last):
  File "/mnt/dietpi_userdata/spotify-connect-web/main.py", line 9, in <module>
    from flask import Flask, request, abort, jsonify, render_template, redirect, flash, url_for
  File "/usr/local/lib/python3.9/dist-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.9/dist-packages/jinja2/__init__.py)
```
And in containers:
```console
root@DietPi:~# journalctl -u spotify-connect-web.service
Jun 06 19:49:25 DietPi systemd[1]: Started spotify-connect-web.service - Spotify Connect Web (DietPi).
Jun 06 19:49:32 DietPi spotify-connect-web[4056]: free(): invalid pointer
Jun 06 19:49:32 DietPi spotify-connect-web[4056]: qemu: uncaught target signal 6 (Aborted) - core dumped
Jun 06 19:49:33 DietPi spotify-connect-web[4051]: qemu: uncaught target signal 6 (Aborted) - core dumped
Jun 06 19:49:33 DietPi systemd[1]: spotify-connect-web.service: Main process exited, code=killed, status=6/ABRT
Jun 06 19:49:33 DietPi systemd[1]: spotify-connect-web.service: Failed with result 'signal'.
Jun 06 19:49:33 DietPi systemd[1]: spotify-connect-web.service: Consumed 5.340s CPU time.
```

**Comment by MichaIng** [comment]
That would be great. Also RPi makes sense in case it is RPi-only.

**Comment by MichaIng** [comment]
Did you reboot once, i.e. is there an audio device available?
```sh
aplay -l
speaker-test -c2
```
It seems to have issue to find the ALSA device, but "default" should actually work with the `/etc/asound.conf` where we define/override the "default" device explicitly. Probably the issues are on a different level. I mean it uses some Python 2.7 and other extremely outdated libraries shipped all with the archive. It aims to be self-contained, but probably it is not 100% and does not work on Bullseye or even not on Buster.

**Comment by MichaIng** [comment]
@Joulinar ping regarding above.

However, as your error message is the same as on my NanoPi M1 with sound device definitely available, it seems to just not work on Bookworm and we should just remove it from `dietpi-software`.

**Comment by Joulinar** [comment]
I was using a RPI3B+ 32bit and soud was available. Yeah I guess we would need to remove it on next release.
