### ISSUE TITLE
DietPi-Software | Include MySQL DB's as DietPi user data

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#672]
eg: move mysql db's to ```/mnt/dietpi_userdata/mysql_store```

Allows users to have MySQL DB's located on USB drive etc.

> http://dietpi.com/phpbb/viewtopic.php?f=9&t=1101&p=4630#p4630

**Comment by Fourdee** [comment]
MySQL:
```
root@DietPi:~# mysql -pdietpi
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 41
Server version: 5.5.53-0+deb8u1 (Debian)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select @@datadir
    -> ;
+-----------------+
| @@datadir       |
+-----------------+
| /var/lib/mysql/ |
+-----------------+
1 row in set (0.00 sec)

```

MariaDB (should be the same, but lets check anyway):
```
root@DietPi:~# mysql -pdietpi
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 16
Server version: 10.0.28-MariaDB-0+deb8u1 (Debian)

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> select @@datadir;
+-----------------+
| @@datadir       |
+-----------------+
| /var/lib/mysql/ |
+-----------------+
1 row in set (0.00 sec)

```

**Comment by Fourdee** [comment]
Notes:
```
systemctl stop mysql
mv /var/lib/mysql /mnt/dietpi_userdata/
ln -sf /mnt/dietpi_userdata/mysql /var/lib/mysql
```

```
root@DietPi:~# ls -lha /var/lib/mysql
lrwxrwxrwx 1 root root 26 Jan  1 14:36 /var/lib/mysql -> /mnt/dietpi_userdata/mysql
```

```
if [ "$(readlink /var/lib/mysql)" != "/mnt/dietpi_userdata/mysql" ]; then

fi
```

**Comment by Fourdee** [comment]
Tests:
- 🈯️ MariaDB + NextCloud
- 🈯️ MySql + NextCloud

- 🈯️ MariaDB reinstall
- 🈯️ MariaDB uninstall

- 🈯️ MySql reinstall
- 🈯️ MySql uninstall

---

Uninstall of MySQL, then reinstall of NextCloud, results in:
```
An unhandled exception has been thrown:
exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'oc_admin'@'localhost' (using password: YES)' in /var/www/nextcloud/lib/private/DB/Connection.php:60
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
```

Appears NextCloud stores information on its installation outside the SQL DB. Expects the original MySQL DB for ```nextcloud``` to exist in its "installed state". Fails to recreate the SQL DB once its originally been installed.

🈯️ Could say, expected behavior for NextCloud if you uninstalled MySQL. Uninstall nextcloud, then reinstalling is the solution.

**Comment by Fourdee** [comment]
We'll also move store (reinstall) for existing locations as a patch in v142

**Comment by Fourdee** [comment]
I'll also include ```/mnt/dietpi_userdata/mysql``` in ```dietpi-backup``` by ~~default~~ optional. Else we will end up with users doing a restore and find the SQL store is not at the correct state.

Created a new ticket for this: 
https://github.com/Fourdee/DietPi/issues/685

**Comment by Fourdee** [comment]
Completed.
