### ISSUE TITLE
MineOS is not being installed 

### ISSUE THREAD

**Issue by boterocamilo** [MichaIng/DietPi#6970]
#### Details:
- Date           | Mon Mar 18 17:05:51 GMT 2024
- Bug report     | 1568fffc-d7e8-4414-b734-9ede76bca
a07
- DietPi version | v9.2.1 (MichaIng/master)
- Image creator  | 
- Pre-image      | 
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux DietPi 6.1.21-v8+ #1642 SM
P PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/L
inux`
- Distro         | bookworm (ID=7,RASPBIAN=0)
- Command        | `npm i --no-audit --no-package-lo
ck posix`
- Exit code      | 7
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- Date           | Mon Mar 18 17:05:51 GMT 2024
- Bug report     | 1568fffc-d7e8-4414-b734-9ede76bcaa07
- DietPi version | v9.2.1 (MichaIng/master)
- Image creator  | 
- Pre-image      | 
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
- Distro         | bookworm (ID=7,RASPBIAN=0)
- Command        | `npm i --no-audit --no-package-lock posix`
- Exit code      | 7
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
>
- ...
#### Extra details:

- ...
#### Additional logs:

```
/usr/local/lib/node_modules/npm/lib/es6/validate-engines.js:31
    throw err
    ^
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass-collect/index.js:4:23)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cacache/lib/get.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
Node.js v21.7.1

---------------------------------------------------------------------
[FAILED] DietPi-Software | Unable to continue, DietPi

    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cacache/lib/get.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)

Node.js v21.7.1

---------------------------------------------------------------------
[FAILED] DietPi-Software | Unable to continue, DietPi-Software will now terminate.
```

**Comment by Joulinar** [comment]
hmm did a test an a Orange Pi5 without issue

```
[ INFO ] DietPi-Software | npm i --no-audit --no-package-lock posix, please wait...
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated passport.socketio@3.6.2: Please check the workaround in https://github.com/jfromaniello/passport.socketio/issues/148
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated angular-sanitize@1.5.11: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated code@1.5.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated angular-translate@2.19.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated angular@1.5.11: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated angular@1.8.3: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated nodeunit@0.11.3: you are strongly encouraged to use other testing options

added 519 packages in 1m

22 packages are looking for funding
  run `npm fund` for details
[  OK  ] DietPi-Software | npm i --no-audit --no-package-lock posix
```

would it be possible to share the whole installation log?

**Comment by MichaIng** [comment]
We install the posix module separately due to a strange bug that happened a while ago: https://github.com/MichaIng/DietPi/issues/5181

Maybe this workaround is not required anymore and maybe without it, the installation works in your case. Can you try, from the error handler, to select "Change command" and replace it with just `true`? This skips the step and just proceeds with the actual MineOS module installation.

**Comment by boterocamilo** [comment]
> We install the posix module separately due to a strange bug that happened a while ago: #5181
> 
> Maybe this workaround is not required anymore and maybe without it, the installation works in your case. Can you try, from the error handler, to select "Change command" and replace it with just `true`? This skips the step and just proceeds with the actual MineOS module installation.

It worked as you suggested. However, I entered twice to "change commamd" and inserted true. After the second one, it worked.
Thanks.

**Comment by MichaIng** [comment]
That sounds like you skipped the MineOS build as well 🤔. Was is previously installed already and this a reinstall/update?

**Comment by boterocamilo** [comment]
> That sounds like you skipped the MineOS build as well 🤔. Was is previously installed already and this a reinstall/update?

It is a new installation, I did not have it before.

**Comment by MichaIng** [comment]
Okay `npm install` installs dependencies only, and it seems all relevant ones have been installed already when the error happened. But still strange. I triggered a test on all arch/distro combinations, just to be sure: https://github.com/MichaIng/DietPi/actions/runs/8344953019

Which Node version is it?
```sh
node -v
```

**Comment by MichaIng** [comment]
Looping through old open issues. Own tests work, and now I see
> Edit 2: My bad, it just needed to add the 'S' to httpS://...

So it did finally work?

Closing this issue. Feel free to reopen if the problem persists.
