### ISSUE TITLE
DietPi-Software | OpenBazaar fails to run

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#784]
> http://dietpi.com/phpbb/viewtopic.php?f=11&t=1406#p5886

**Comment by Fourdee** [comment]
Confirmed on C2. Install log:
http://pastebin.com/4mc6y47H

**Comment by Fourdee** [comment]
Looks like ```pip``` is up the fritz:
```
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    from setuptools import Distribution, setup
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named packaging.version
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named packaging.version
```

- 🈯️ solution, install latest pip: https://github.com/pypa/setuptools/issues/937#issuecomment-277276387

---

Software we install that uses pip:
- 🈯️ mopidy
- 🈯️ openbazaar
- 🈯️ emonhub

.
- 🈯️ Create new linux software entry for ```pip```, add prereq to above software

**Comment by Fourdee** [comment]
Completed.
